POST  http://localhost:3000/campaigns

{
  "Name": "Campanha de Teste",
  "Content": "Conteúdo da campanha de teste",
  "Emails": ["email1@example.com", "email2@example.com"]
}


###

GET  http://localhost:3000/campaigns